/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Nov 29 16:31:11 2017. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CmdRespAuthParams_fields[5] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, CmdRespAuthParams, timestamp, timestamp, 0),
    PB_FIELD(  2, FIXED32 , REQUIRED, STATIC  , OTHER, CmdRespAuthParams, random, timestamp, 0),
    PB_FIELD(  3, FIXED32 , REQUIRED, STATIC  , OTHER, CmdRespAuthParams, random2, random, 0),
    PB_FIELD(  4, FIXED32 , REQUIRED, STATIC  , OTHER, CmdRespAuthParams, random3, random2, 0),
    PB_LAST_FIELD
};

const pb_field_t CmdTwoStateParams_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CmdTwoStateParams, state, state, 0),
    PB_LAST_FIELD
};

const pb_field_t StoreInformation_fields[4] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, StoreInformation, timestamp, timestamp, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, StoreInformation, temperture, timestamp, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, StoreInformation, humidity, temperture, 0),
    PB_LAST_FIELD
};

const pb_field_t RespGetdataParams_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, RespGetdataParams, info, info, &StoreInformation_fields),
    PB_LAST_FIELD
};

const pb_field_t RespGetDeviceParams_fields[5] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, RespGetDeviceParams, device_id, device_id, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, RespGetDeviceParams, led_status, device_id, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, RespGetDeviceParams, beep_status, led_status, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, RespGetDeviceParams, is_registered, beep_status, 0),
    PB_LAST_FIELD
};

const pb_field_t RequestMessage_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, RequestMessage, frametype, frametype, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, RequestMessage, cmd, frametype, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, RequestMessage, cmd_resp, cmd, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, RequestMessage, params, cmd_resp, 0),
    PB_LAST_FIELD
};







/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RespGetdataParams, info[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_CmdRespAuthParams_CmdTwoStateParams_StoreInformation_RespGetdataParams_RespGetDeviceParams_RequestMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RespGetdataParams, info[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_CmdRespAuthParams_CmdTwoStateParams_StoreInformation_RespGetdataParams_RespGetDeviceParams_RequestMessage)
#endif


/* @@protoc_insertion_point(eof) */
