/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Thu Nov 23 14:10:10 2017. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t StoreInformation_fields[4] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, StoreInformation, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, StoreInformation, temperture, timestamp, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, StoreInformation, humidity, temperture, 0),
    PB_LAST_FIELD
};

const pb_field_t TransInformation_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, TransInformation, info, info, &StoreInformation_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceInfo_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, DeviceInfo, device_id, device_id, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, DeviceInfo, led_status, device_id, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, DeviceInfo, beep_status, led_status, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, DeviceInfo, is_registered, beep_status, 0),
    PB_LAST_FIELD
};

const pb_field_t RequestMessage_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, RequestMessage, frametype, frametype, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, RequestMessage, cmd, frametype, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, RequestMessage, cmd_resp, cmd, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, CALLBACK, OTHER, RequestMessage, params, cmd_resp, 0),
    PB_LAST_FIELD
};







/* @@protoc_insertion_point(eof) */
